# -*- coding: utf-8 -*-
"""TFG__LLM_sentiment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1un3KEtRgw71dIJIZcwekNReiTRlbFvPM

# 1. PRIMERA PARTE - MODELO PRINCIPAL
"""

!pip install -q bitsandbytes accelerate psutil huggingface_hub datasets transformers

#Importamos todo lo necesario para ejecutar el código y hacemos algunas configuraciones

import torch
import psutil
import os
import time
import json
import gc
import numpy as np
from transformers import AutoModelForCausalLM, AutoTokenizer, BitsAndBytesConfig
from datasets import load_dataset

device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Dispositivo: {device}")
if device == "cuda":
   print(f"GPU: {torch.cuda.get_device_name(0)}")
   print(f"VRAM total: {torch.cuda.get_device_properties(0).total_memory / 1e9:.2f} GB")
else:
   print("⚠️ NO HAY GPU.")

bnb_config = BitsAndBytesConfig(
   load_in_4bit=True,
   bnb_4bit_quant_type="nf4",
   bnb_4bit_compute_dtype=torch.float16,
)

#Modelos a analizar

MODELOS = {
   "LLaMA 3.1 8B Instruct": "meta-llama/Llama-3.1-8B-Instruct",
   "Qwen 2.5 7B Instruct": "Qwen/Qwen2.5-7B-Instruct",
   "Mistral 7B Instruct": "mistralai/Mistral-7B-Instruct-v0.3",
}

# Hugging Face configuration - log in

from huggingface_hub import login
login()

from google.colab import drive
drive.mount('/content/drive')

# Dataset Amazon Reviews Multi (Español) - descarga

print("Cargando Amazon Reviews Multi (español)...")
try:
   amazon_ds = load_dataset("mteb/amazon_reviews_multi", "es", split="test")
except Exception as e1:
   print(f"Método 1 falló: {e1}")
   try:
       amazon_ds = load_dataset("amazon_reviews_multi", "es", split="test")
   except Exception as e2:
       print(f"Método 2 falló: {e2}")
       amazon_ds = load_dataset(
           "json",
           data_files="https://huggingface.co/datasets/mteb/amazon_reviews_multi/resolve/main/es/test.jsonl",
           split="train",
       )

print(f"Total reseñas: {len(amazon_ds)}")
print(f"Columnas: {amazon_ds.column_names}")
print(f"Ejemplo: {amazon_ds[0]}")

resenas_latencia = [r["text"] for r in amazon_ds.select(range(50))]
print(f"Reseñas seleccionadas para latencia: {len(resenas_latencia)}")

#Descarga del otro dataset para el calculo de perplejidad.

print("Cargando WikiText-2...")
wikitext = load_dataset("wikitext", "wikitext-2-raw-v1", split="test")
wikitext_text = "\n".join([t for t in wikitext["text"] if t.strip()])
print(f"WikiText-2 cargado: {len(wikitext_text)} caracteres")

# Calculamos las métricas para la selección del modelo principal

def medir_tamano_modelo(model_name):
   from huggingface_hub import model_info
   try:
       info = model_info(model_name)
       total = 0
       if info.siblings:
           for sibling in info.siblings:
               if sibling.rfilename.endswith((".safetensors", ".bin")):
                   if sibling.size is not None:
                       total += sibling.size
       if total > 0:
           return total / 1e9
       if hasattr(info, "safetensors") and info.safetensors:
           params = info.safetensors.get("total", 0)
           return (params * 2) / 1e9
   except Exception as e:
       print(f"  ⚠️ No se pudo obtener tamaño via API: {e}")
   print("  Usando estimación por defecto")
   return 0.0


def medir_ram_vram():
   ram = psutil.Process(os.getpid()).memory_info().rss / 1e9
   vram = torch.cuda.memory_allocated() / 1e9 if torch.cuda.is_available() else 0
   vram_peak = torch.cuda.max_memory_allocated() / 1e9 if torch.cuda.is_available() else 0
   return {"ram_gb": round(ram, 2), "vram_gb": round(vram, 2), "vram_peak_gb": round(vram_peak, 2)}


def medir_latencia(model, tokenizer, resenas, max_new_tokens=30):
   tiempos = []
   tokens_generados = []
   for i, resena in enumerate(resenas):
       prompt = (
           "Clasifica el sentimiento de la siguiente reseña como positivo, "
           "negativo o neutro. Responde únicamente con una palabra.\n\n"
           f"Reseña: {resena}\n\nSentimiento:"
       )
       inputs = tokenizer(
           prompt, return_tensors="pt", truncation=True, max_length=512
       ).to(device)
       if torch.cuda.is_available():
           torch.cuda.synchronize()
       t0 = time.time()
       with torch.no_grad():
           outputs = model.generate(
               **inputs,
               max_new_tokens=max_new_tokens,
               do_sample=False,
               pad_token_id=tokenizer.pad_token_id,
           )
       if torch.cuda.is_available():
           torch.cuda.synchronize()
       t1 = time.time()
       n_tokens = outputs.shape[1] - inputs["input_ids"].shape[1]
       tiempos.append(t1 - t0)
       tokens_generados.append(n_tokens)
       if (i + 1) % 10 == 0:
           print(f"  Procesadas {i + 1}/{len(resenas)} reseñas...")
   tiempo_total = sum(tiempos)
   total_tokens = sum(tokens_generados)
   return {
       "tiempo_medio_por_resena_s": round(np.mean(tiempos), 3),
       "tokens_por_segundo": round(total_tokens / tiempo_total, 2) if tiempo_total > 0 else 0,
       "tiempo_total_s": round(tiempo_total, 2),
       "resenas_procesadas": len(resenas),
   }


def medir_perplejidad(model, tokenizer, texto, max_length=512, stride=256):
   encodings = tokenizer(texto, return_tensors="pt", truncation=True, max_length=50000)
   input_ids = encodings.input_ids.to(device)
   seq_len = input_ids.size(1)
   print(f"  Tokens totales WikiText-2: {seq_len}")
   nlls = []
   n_chunks = 0
   for begin in range(0, seq_len, stride):
       end = min(begin + max_length, seq_len)
       input_chunk = input_ids[:, begin:end]
       target_chunk = input_chunk.clone()
       if begin > 0:
           overlap = begin + max_length - end
           if overlap > 0:
               target_chunk[:, :max_length - (end - begin)] = -100
       with torch.no_grad():
           outputs = model(input_chunk, labels=target_chunk)
           nll = outputs.loss
       if not torch.isnan(nll) and not torch.isinf(nll):
           nlls.append(nll.item())
       n_chunks += 1
       if end == seq_len:
           break
   if not nlls:
       print("  ⚠️ No se pudieron calcular NLLs válidos")
       return float("inf")
   ppl = np.exp(np.mean(nlls))
   print(f"  Chunks procesados: {n_chunks}, NLLs válidos: {len(nlls)}")
   return round(ppl, 2)


def limpiar_memoria():
   gc.collect()
   if torch.cuda.is_available():
       torch.cuda.empty_cache()
       torch.cuda.reset_peak_memory_stats()
   gc.collect()
   time.sleep(2)


def evaluar_modelo(nombre, repo, bnb_config):
   print(f"\n{'='*60}")
   print(f"=== {nombre} ===")
   print(f"{'='*60}\n")

   print("Midiendo tamaño en disco...")
   tamano = medir_tamano_modelo(repo)
   print(f"Tamaño en disco (original float16): {tamano:.2f} GB\n")

   limpiar_memoria()
   mem_antes = medir_ram_vram()
   print(f"Memoria antes de cargar: {mem_antes}")

   print("Cargando modelo (cuantización 4-bit con bitsandbytes)...")
   tokenizer = AutoTokenizer.from_pretrained(repo, trust_remote_code=True)
   if tokenizer.pad_token is None:
       tokenizer.pad_token = tokenizer.eos_token
       tokenizer.pad_token_id = tokenizer.eos_token_id

   model = AutoModelForCausalLM.from_pretrained(
       repo,
       quantization_config=bnb_config,
       device_map="auto",
       trust_remote_code=True,
   )
   model.eval()
   mem_carga = medir_ram_vram()
   print(f"Memoria después de cargar: {mem_carga}")

   print("\nMidiendo latencia (50 reseñas)...")
   latencia = medir_latencia(model, tokenizer, resenas_latencia)
   print(f"Latencia: {latencia}")
   mem_inferencia = medir_ram_vram()
   print(f"Memoria después de inferencia: {mem_inferencia}")

   print("\nMidiendo perplejidad (WikiText-2)...")
   ppl = medir_perplejidad(model, tokenizer, wikitext_text)
   print(f"Perplejidad: {ppl}")

   resultado = {
       "modelo": nombre,
       "tamano_disco_gb": round(tamano, 2),
       "vram_carga_gb": mem_carga["vram_gb"],
       "vram_peak_gb": mem_inferencia["vram_peak_gb"],
       "ram_carga_gb": mem_carga["ram_gb"],
       "tokens_por_segundo": latencia["tokens_por_segundo"],
       "tiempo_medio_resena_s": latencia["tiempo_medio_por_resena_s"],
       "perplejidad": ppl,
   }
   print(f"\n--- RESUMEN {nombre} ---")
   print(json.dumps(resultado, indent=2, ensure_ascii=False))

   del model, tokenizer
   limpiar_memoria()

   return resultado

#Llamamos al modelo LLaMa

try:
   resultado_llama = evaluar_modelo(
       "LLaMA 3.1 8B Instruct", MODELOS["LLaMA 3.1 8B Instruct"], bnb_config
   )
except Exception as e:
   print(f"❌ ERROR en LLaMA: {e}")
   resultado_llama = None
   limpiar_memoria()

#Llamamos al modelo Qwen

try:
   resultado_qwen = evaluar_modelo(
       "Qwen 2.5 7B Instruct", MODELOS["Qwen 2.5 7B Instruct"], bnb_config
   )
except Exception as e:
   print(f"❌ ERROR en Qwen: {e}")
   resultado_qwen = None
   limpiar_memoria()

# Llamamos al modelo Mistral

try:
   resultado_mistral = evaluar_modelo(
       "Mistral 7B Instruct", MODELOS["Mistral 7B Instruct"], bnb_config
   )
except Exception as e:
   print(f"❌ ERROR en Mistral: {e}")
   resultado_mistral = None
   limpiar_memoria()

#Creacion de una tabla resumen con la información del anaálisis

print("\n" + "=" * 80)
print("TABLA RESUMEN — SELECCIÓN DE LLM CUANTIZADO")
print("=" * 80)

resultados = {
   "LLaMA 3.1 8B": resultado_llama,
   "Qwen 2.5 7B": resultado_qwen,
   "Mistral 7B": resultado_mistral,
}

resultados_ok = {k: v for k, v in resultados.items() if v is not None}

if resultados_ok:
   nombres = list(resultados_ok.keys())
   header = f"{'Métrica':<30}" + "".join(f"{n:>18}" for n in nombres)
   print(header)
   print("-" * len(header))
   for key, label in [
       ("tamano_disco_gb", "Tamaño disco (GB)"),
       ("vram_carga_gb", "VRAM carga (GB)"),
       ("vram_peak_gb", "VRAM pico (GB)"),
       ("ram_carga_gb", "RAM sistema (GB)"),
       ("tokens_por_segundo", "Tokens/segundo"),
       ("tiempo_medio_resena_s", "Tiempo/reseña (s)"),
       ("perplejidad", "Perplejidad"),
   ]:
       row = f"{label:<30}"
       for n in nombres:
           row += f"{resultados_ok[n][key]:>18}"
       print(row)
   print("=" * len(header))
else:
   print("❌ Ningún modelo se evaluó correctamente.")

fallidos = [k for k, v in resultados.items() if v is None]
if fallidos:
   print(f"\n⚠️ Modelos con error: {', '.join(fallidos)}")

print("\n✅ Copia estos resultados para redactar el análisis en el Cap. 4 del TFG.")

"""2. SEGUNDA PARTE - PROMPTING, ANALISIS DEL PERFORMANCE"""

!pip install -q bitsandbytes accelerate psutil huggingface_hub datasets transformers scikit-learn

#ejecuta esta celda primero, luego reinicia el entorno, es necesario ya que se deben de desacar bien los paquetes. (runtime,restart session)
#antes de correr esto recuerda reiniciar el entorno, ya que la primera parte ocupa mucha memoria.

# Importamos paquetes

import torch
import os
import time
import json
import gc
import re
import numpy as np
from transformers import AutoModelForCausalLM, AutoTokenizer, BitsAndBytesConfig
from datasets import load_dataset
from sklearn.metrics import (
   accuracy_score, precision_score, recall_score, f1_score,
   confusion_matrix,
)

device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Dispositivo: {device}")
if device == "cuda":
   print(f"GPU: {torch.cuda.get_device_name(0)}")
   print(f"VRAM total: {torch.cuda.get_device_properties(0).total_memory / 1e9:.2f} GB")

bnb_config = BitsAndBytesConfig(
   load_in_4bit=True,
   bnb_4bit_quant_type="nf4",
   bnb_4bit_compute_dtype=torch.float16,
)

#Login en Huggingface
from huggingface_hub import login
login()

# Nos descargamos el dataste (200 reseñas)

print("Cargando Amazon Reviews Multi (español)...")
try:
   amazon_ds = load_dataset("mteb/amazon_reviews_multi", "es", split="test")
except Exception:
   amazon_ds = load_dataset(
       "json",
       data_files="https://huggingface.co/datasets/mteb/amazon_reviews_multi/resolve/main/es/test.jsonl",
       split="train",
   )

def mapear_label(label):
   if label <= 1:
       return "negativo"
   elif label == 2:
       return "neutro"
   else:
       return "positivo"

ejemplos_por_clase = {"positivo": None, "negativo": None, "neutro": None}
indices_ejemplos = set()
for i, r in enumerate(amazon_ds):
   clase = mapear_label(r["label"])
   if ejemplos_por_clase[clase] is None:
       ejemplos_por_clase[clase] = r["text"]
       indices_ejemplos.add(i)
   if all(v is not None for v in ejemplos_por_clase.values()):
       break

print("Ejemplos reales para prompts:")
for clase, texto in ejemplos_por_clase.items():
   print(f"  {clase}: {texto[:80]}...")

np.random.seed(42)
indices_disponibles = [i for i in range(len(amazon_ds)) if i not in indices_ejemplos]
indices = np.random.choice(indices_disponibles, size=200, replace=False)
subset = amazon_ds.select(indices.tolist())

textos = [r["text"] for r in subset]
labels_true = [mapear_label(r["label"]) for r in subset]

print(f"\nReseñas para evaluación: {len(textos)}")
from collections import Counter
print(f"Distribución: {Counter(labels_true)}")

# Prompting

CLASES_VALIDAS = {"positivo", "negativo", "neutro"}
EJ_POS = ejemplos_por_clase["positivo"]
EJ_NEG = ejemplos_por_clase["negativo"]
EJ_NEU = ejemplos_por_clase["neutro"]

def prompt_zero_shot(resena):
   return (
       "Clasifica el sentimiento de la siguiente reseña como positivo, "
       "negativo o neutro. Responde únicamente con una palabra.\n\n"
       f"Reseña: {resena}\n\nSentimiento:"
   )

def prompt_one_shot(resena):
   return (
       "Clasifica el sentimiento de la siguiente reseña como positivo, "
       "negativo o neutro. Responde únicamente con una palabra.\n\n"
       "Ejemplo:\n"
       f"Reseña: {EJ_POS}\n"
       "Sentimiento: positivo\n\n"
       f"Reseña: {resena}\n\nSentimiento:"
   )

def prompt_few_shot(resena):
   return (
       "Clasifica el sentimiento de la siguiente reseña como positivo, "
       "negativo o neutro. Responde únicamente con una palabra.\n\n"
       f"Ejemplo 1:\nReseña: {EJ_POS}\nSentimiento: positivo\n\n"
       f"Ejemplo 2:\nReseña: {EJ_NEG}\nSentimiento: negativo\n\n"
       f"Ejemplo 3:\nReseña: {EJ_NEU}\nSentimiento: neutro\n\n"
       f"Reseña: {resena}\n\nSentimiento:"
   )

def prompt_cot(resena):
   return (
       "Clasifica el sentimiento de la siguiente reseña como positivo, "
       "negativo o neutro.\n\n"
       "Piensa paso a paso:\n"
       "1. Identifica las palabras clave que expresan sentimiento.\n"
       "2. Determina si el tono general es positivo, negativo o neutro.\n"
       "3. Responde con una única palabra: positivo, negativo o neutro.\n\n"
       f"Reseña: {resena}\n\nAnálisis y sentimiento:"
   )

def prompt_role_based(resena):
   return (
       "Eres un experto en análisis de sentimientos con amplia experiencia "
       "en reseñas de productos de comercio electrónico. "
       "Clasifica el sentimiento de la siguiente reseña como positivo, "
       "negativo o neutro. Responde únicamente con una palabra.\n\n"
       f"Reseña: {resena}\n\nSentimiento:"
   )

def prompt_iterative_fase1(resena):
   return (
       "Clasifica el sentimiento de la siguiente reseña como positivo, "
       "negativo o neutro. Responde únicamente con una palabra.\n\n"
       f"Reseña: {resena}\n\nSentimiento:"
   )

def prompt_iterative_fase2(resena, clasificacion_previa):
   return (
       f"Has clasificado la siguiente reseña como \"{clasificacion_previa}\".\n\n"
       f"Reseña: {resena}\n\n"
       "Revisa tu clasificación. ¿Es correcta? Si no, corrígela. "
       "Responde únicamente con una palabra: positivo, negativo o neutro.\n\n"
       "Sentimiento final:"
   )

TECNICAS = {
   "zero_shot": prompt_zero_shot,
   "one_shot": prompt_one_shot,
   "few_shot": prompt_few_shot,
   "cot": prompt_cot,
   "role_based": prompt_role_based,
   "iterative": None,
}

# Funciones

def parsear_sentimiento(texto):
   texto = texto.lower().strip()
   matches = list(re.finditer(r"\b(positivo|negativo|neutro)\b", texto))
   if matches:
       return matches[-1].group(1)
   return "no_clasificado"

def generar_respuesta(model, tokenizer, prompt, max_new_tokens=50):
   inputs = tokenizer(
       prompt, return_tensors="pt", truncation=True, max_length=512
   ).to(device)
   with torch.no_grad():
       outputs = model.generate(
           **inputs,
           max_new_tokens=max_new_tokens,
           do_sample=False,
           pad_token_id=tokenizer.pad_token_id,
       )
   return tokenizer.decode(
       outputs[0][inputs["input_ids"].shape[1]:], skip_special_tokens=True
   )

def evaluar_tecnica(model, tokenizer, textos, labels_true, tecnica_nombre, prompt_fn):
   predicciones = []
   detalles = []
   for i, resena in enumerate(textos):
       if tecnica_nombre == "iterative":
           p1 = prompt_iterative_fase1(resena)
           r1 = generar_respuesta(model, tokenizer, p1)
           clasif1 = parsear_sentimiento(r1)
           p2 = prompt_iterative_fase2(resena, clasif1)
           r2 = generar_respuesta(model, tokenizer, p2)
           pred = parsear_sentimiento(r2)
           detalles.append({
               "resena": resena, "prompt_fase1": p1, "respuesta_fase1": r1,
               "clasificacion_fase1": clasif1, "prompt_fase2": p2,
               "respuesta_fase2": r2, "prediccion_final": pred,
           })
       elif tecnica_nombre == "cot":
           p = prompt_fn(resena)
           resp = generar_respuesta(model, tokenizer, p, max_new_tokens=150)
           pred = parsear_sentimiento(resp)
           detalles.append({"resena": resena, "prompt": p, "respuesta_cruda": resp, "prediccion": pred})
       else:
           p = prompt_fn(resena)
           resp = generar_respuesta(model, tokenizer, p)
           pred = parsear_sentimiento(resp)
           detalles.append({"resena": resena, "prompt": p, "respuesta_cruda": resp, "prediccion": pred})
       predicciones.append(pred)
       if (i + 1) % 50 == 0:
           print(f"    {tecnica_nombre}: {i + 1}/{len(textos)} reseñas procesadas")
   return predicciones, detalles

def calcular_metricas(y_true, y_pred):
   clases = ["positivo", "negativo", "neutro"]
   no_clasif = sum(1 for p in y_pred if p not in CLASES_VALIDAS)
   y_pred_eval = [p if p in CLASES_VALIDAS else "neutro" for p in y_pred]
   acc = accuracy_score(y_true, y_pred_eval)
   prec = precision_score(y_true, y_pred_eval, labels=clases, average=None, zero_division=0)
   rec = recall_score(y_true, y_pred_eval, labels=clases, average=None, zero_division=0)
   f1 = f1_score(y_true, y_pred_eval, labels=clases, average=None, zero_division=0)
   f1_macro = f1_score(y_true, y_pred_eval, labels=clases, average="macro", zero_division=0)
   cm = confusion_matrix(y_true, y_pred_eval, labels=clases)
   return {
       "accuracy": round(acc, 4),
       "precision": {c: round(p, 4) for c, p in zip(clases, prec)},
       "recall": {c: round(r, 4) for c, r in zip(clases, rec)},
       "f1": {c: round(f, 4) for c, f in zip(clases, f1)},
       "f1_macro": round(f1_macro, 4),
       "confusion_matrix": cm.tolist(),
       "no_clasificado": no_clasif,
   }

def bootstrap_f1_macro(y_true, y_pred, n_bootstrap=1000, ci=0.95):
   clases = ["positivo", "negativo", "neutro"]
   y_true, y_pred = np.array(y_true), np.array(y_pred)
   np.random.seed(42)
   f1_scores = []
   for _ in range(n_bootstrap):
       idx = np.random.choice(len(y_true), size=len(y_true), replace=True)
       f1_scores.append(f1_score(y_true[idx], y_pred[idx], labels=clases, average="macro", zero_division=0))
   lower = np.percentile(f1_scores, (1 - ci) / 2 * 100)
   upper = np.percentile(f1_scores, (1 + ci) / 2 * 100)
   return round(lower, 4), round(upper, 4)

def limpiar_memoria():
   gc.collect()
   if torch.cuda.is_available():
       torch.cuda.empty_cache()
       torch.cuda.reset_peak_memory_stats()
   gc.collect()
   time.sleep(2)

# Modelo y función principal

MODELOS = {
   "LLaMA 3.1 8B Instruct": "meta-llama/Llama-3.1-8B-Instruct",
   "Qwen 2.5 7B Instruct": "Qwen/Qwen2.5-7B-Instruct",
   "Mistral 7B Instruct": "mistralai/Mistral-7B-Instruct-v0.3",
}

tecnicas_nombres = ["zero_shot", "one_shot", "few_shot", "cot", "role_based", "iterative"]
res_llama = None
res_qwen = None
res_mistral = None

def guardar_parcial():
   parcial = {}
   for nombre, res in [("LLaMA 3.1 8B", res_llama), ("Qwen 2.5 7B", res_qwen), ("Mistral 7B", res_mistral)]:
       if res is not None:
           parcial[nombre] = {
               tec: {"metricas": res[tec]["metricas"], "predicciones": res[tec]["predicciones"], "detalles": res[tec]["detalles"]}
               for tec in tecnicas_nombres
           }
   if parcial:
       with open("resultados_parciales.json", "w", encoding="utf-8") as f:
           json.dump(parcial, f, ensure_ascii=False, indent=2)
       print(f"💾 Guardados {len(parcial)} modelo(s) en resultados_parciales.json — DESCÁRGALO AHORA")

def evaluar_modelo_completo(nombre, repo):
   print(f"\n{'='*70}")
   print(f"=== {nombre} ===")
   print(f"{'='*70}")
   limpiar_memoria()
   print("Cargando modelo...")
   tokenizer = AutoTokenizer.from_pretrained(repo, trust_remote_code=True)
   if tokenizer.pad_token is None:
       tokenizer.pad_token = tokenizer.eos_token
       tokenizer.pad_token_id = tokenizer.eos_token_id
   model = AutoModelForCausalLM.from_pretrained(
       repo, quantization_config=bnb_config, device_map="auto", trust_remote_code=True,
   )
   model.eval()
   print("Modelo cargado.\n")
   resultados_modelo = {}
   for tecnica_nombre, prompt_fn in TECNICAS.items():
       print(f"\n  --- Técnica: {tecnica_nombre} ---")
       t0 = time.time()
       predicciones, detalles = evaluar_tecnica(model, tokenizer, textos, labels_true, tecnica_nombre, prompt_fn)
       t1 = time.time()
       print(f"    Tiempo: {t1 - t0:.1f}s")
       pred_eval = [p if p in CLASES_VALIDAS else "neutro" for p in predicciones]
       metricas = calcular_metricas(labels_true, predicciones)
       ci_lower, ci_upper = bootstrap_f1_macro(labels_true, pred_eval)
       metricas["f1_macro_ci_95"] = [ci_lower, ci_upper]
       metricas["tiempo_total_s"] = round(t1 - t0, 1)
       resultados_modelo[tecnica_nombre] = {"metricas": metricas, "predicciones": predicciones, "detalles": detalles}
       print(f"    F1-macro: {metricas['f1_macro']:.4f} [{ci_lower:.4f}, {ci_upper:.4f}]")
       print(f"    Accuracy: {metricas['accuracy']:.4f}")
       print(f"    No clasificados: {metricas['no_clasificado']}")
   del model, tokenizer
   limpiar_memoria()
   return resultados_modelo

# Piloto

print("PILOTO: 20 reseñas con Mistral")
limpiar_memoria()
tok = AutoTokenizer.from_pretrained("mistralai/Mistral-7B-Instruct-v0.3", trust_remote_code=True)
if tok.pad_token is None:
   tok.pad_token = tok.eos_token
   tok.pad_token_id = tok.eos_token_id
mod = AutoModelForCausalLM.from_pretrained(
   "mistralai/Mistral-7B-Instruct-v0.3",
   quantization_config=bnb_config, device_map="auto", trust_remote_code=True,
)
mod.eval()
for tec, fn in TECNICAS.items():
   preds, det = evaluar_tecnica(mod, tok, textos[:20], labels_true[:20], tec, fn)
   ok = sum(1 for p, l in zip(preds, labels_true[:20]) if p == l)
   nc = sum(1 for p in preds if p not in CLASES_VALIDAS)
   print(f"  {tec:15s} | Correctas: {ok}/20 | No clasif: {nc}")
del mod, tok
limpiar_memoria()
print("✅ Piloto completado.")

#LLaMa
try:
   res_llama = evaluar_modelo_completo("LLaMA 3.1 8B Instruct", MODELOS["LLaMA 3.1 8B Instruct"])
   guardar_parcial()
except Exception as e:
   print(f"❌ ERROR en LLaMA: {e}")
   res_llama = None
   limpiar_memoria()

# Qwen
try:
   res_qwen = evaluar_modelo_completo("Qwen 2.5 7B Instruct", MODELOS["Qwen 2.5 7B Instruct"])
   guardar_parcial()
except Exception as e:
   print(f"❌ ERROR en Qwen: {e}")
   res_qwen = None
   limpiar_memoria()

# Mistral

try:
   res_mistral = evaluar_modelo_completo("Mistral 7B Instruct", MODELOS["Mistral 7B Instruct"])
   guardar_parcial()
except Exception as e:
   print(f"❌ ERROR en Mistral: {e}")
   res_mistral = None
   limpiar_memoria()

import json

# =============================================================================
# CARGA DE RESULTADOS
# =============================================================================
# Los resultados se ejecutaron en sesiones separadas por limitaciones de GPU
# de Google Colab gratuito. Cada modelo generó un archivo JSON parcial que
# se combina aquí para el análisis conjunto.

with open("resultados_parciales_Llama.json", "r", encoding="utf-8") as f:
   datos_llama = json.load(f)
with open("resultados_parciales_Qwen.json", "r", encoding="utf-8") as f:
   datos_qwen = json.load(f)
with open("resultados_parciales_Mistral.json", "r", encoding="utf-8") as f:
   datos_mistral = json.load(f)

combinado = {}
combinado.update(datos_llama)
combinado.update(datos_qwen)
combinado.update(datos_mistral)

tecnicas_nombres = ["zero_shot", "one_shot", "few_shot", "cot", "role_based", "iterative"]
print(f"Modelos cargados: {list(combinado.keys())}")

# =============================================================================
# 1. TABLA RESUMEN GENERAL — F1-MACRO POR MODELO Y TÉCNICA
# =============================================================================
# Muestra el F1-macro con intervalo de confianza al 95% (bootstrap)
# para cada combinación modelo × técnica de prompting.

print("\n" + "=" * 90)
print("1. TABLA RESUMEN — F1-MACRO POR MODELO Y TÉCNICA DE PROMPTING")
print("=" * 90)
nombres = list(combinado.keys())
header = f"{'Técnica':<20}" + "".join(f"{n:>25}" for n in nombres)
print(header)
print("-" * len(header))
for tec in tecnicas_nombres:
   row = f"{tec:<20}"
   for n in nombres:
       m = combinado[n][tec]["metricas"]
       ci = m["f1_macro_ci_95"]
       row += f"{m['f1_macro']:.4f} [{ci[0]:.4f},{ci[1]:.4f}]".rjust(25)
   print(row)
print("=" * len(header))

# =============================================================================
# 2. RESUMEN POR MODELO — MEJOR Y PEOR TÉCNICA
# =============================================================================
# Para cada modelo, muestra el accuracy y F1-macro de cada técnica,
# e identifica la mejor y peor técnica según F1-macro.

print("\n" + "=" * 90)
print("2. RESUMEN POR MODELO")
print("=" * 90)
for nombre_modelo, res in combinado.items():
   print(f"\n  {'─'*60}")
   print(f"  {nombre_modelo}")
   print(f"  {'─'*60}")
   print(f"  {'Técnica':<20} {'Accuracy':>10} {'F1-macro':>10} {'No clasif':>10}")
   print(f"  {'-'*50}")
   mejor_f1, peor_f1 = -1, 2
   mejor_tec, peor_tec = "", ""
   for tec in tecnicas_nombres:
       m = res[tec]["metricas"]
       print(f"  {tec:<20} {m['accuracy']:>10.4f} {m['f1_macro']:>10.4f} {m['no_clasificado']:>10}")
       if m["f1_macro"] > mejor_f1:
           mejor_f1 = m["f1_macro"]
           mejor_tec = tec
       if m["f1_macro"] < peor_f1:
           peor_f1 = m["f1_macro"]
           peor_tec = tec
   print(f"\n  ✅ Mejor técnica: {mejor_tec} (F1-macro: {mejor_f1:.4f})")
   print(f"  ❌ Peor técnica:  {peor_tec} (F1-macro: {peor_f1:.4f})")

# =============================================================================
# 3. DETALLE COMPLETO POR MODELO — TODAS LAS MÉTRICAS
# =============================================================================
# Para cada modelo y técnica: accuracy, F1-macro con IC 95%, precision,
# recall y F1 por clase, número de no clasificados, y matriz de confusión.

print("\n" + "=" * 90)
print("3. DETALLE COMPLETO POR MODELO")
print("=" * 90)
for nombre_modelo, res in combinado.items():
   print(f"\n{'='*70}")
   print(f"DETALLE: {nombre_modelo}")
   print(f"{'='*70}")
   for tec in tecnicas_nombres:
       m = res[tec]["metricas"]
       print(f"\n  {tec}:")
       print(f"    Accuracy:  {m['accuracy']:.4f}")
       print(f"    F1-macro:  {m['f1_macro']:.4f} {m['f1_macro_ci_95']}")
       print(f"    No clasif: {m['no_clasificado']}")
       print(f"    Precision: {m['precision']}")
       print(f"    Recall:    {m['recall']}")
       print(f"    F1/clase:  {m['f1']}")
       print(f"    Matriz de confusión (pos/neg/neu):")
       for fila in m["confusion_matrix"]:
           print(f"      {fila}")

# =============================================================================
# GUARDAR ARCHIVO ÚNICO CON TODOS LOS RESULTADOS
# =============================================================================
with open("resultados_completos.json", "w", encoding="utf-8") as f:
   json.dump(combinado, f, ensure_ascii=False, indent=2)

print(f"\n✅ Archivo único guardado: resultados_completos.json")
print(f"Modelos incluidos: {list(combinado.keys())}")
print("DESCÁRGALO desde el panel de archivos de Colab (carpeta a la izquierda).")